project/core/views.py
from project import db
from project.users.models import Users
from werkzeug.security import generate_password_hash
from flask import render_template, Blueprint, request, redirect, url_for


core_blueprint = Blueprint('core', __name__, template_folder='templates', static_folder='static')


@core_blueprint.route('/', methods=['GET','POST'])
def index():

    errors = []
    if request.method == 'POST':

        email = request.form['emailID']
        insta_username = request.form['InstaID']
        password = request.form['Password']
        confirm_password = request.form['Con_Password']
        phone_number = request.form['telNumber']

        errors = list()
        try:
            phone_number = int(phone_number)
        except:
            errors.append("Invalid Phone Number")


        if password != confirm_password:
            errors.append("Password does not match")

        if type(phone_number) == int and (password == confirm_password):

            new_user = Users(email=email,
                             insta_username=insta_username,
                             hashed_password=generate_password_hash(password),
                             mob_number=phone_number)
            db.session.add(new_user)
            db.session.commit()

            return redirect(url_for('users.login'))
    return render_template('index.html', errors=errors)



@core_blueprint.route('/pricing')
def pricing():
    return render_template('Pricing.html')


@core_blueprint.route('/faq')
def faq():
    return render_template('FAQ.html')

@core_blueprint.route('/contact')
def contact():
    return render_template('Contact.html')

project/users/views.py
import sys
import time
import requests
import datetime
from project import db
from datetime import timedelta
# from project.users.models import Users, Counter
from project.users.request_acceptor import InstagramBot
from flask_login import login_required, login_user, logout_user, current_user
from flask import Blueprint, render_template, redirect, url_for, request, session
import memcache as client


sys.path.append('../../')


users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/request_accepted_counter', methods=['GET', 'POST'])
def request_accepted_counter():
    try:
        if Counter:
            counterval = client.get(session['insta_username']) 
			# Counter.query.filter_by(insta_username=session['insta_username']).first()
    except:
        time.sleep(0.10)
        ctr = "0"
    # except sqlite3.OperationalError as e:
    #     print('[-] Sqlite operational error: {} Retrying...'.format(e))
    #     ctr = "0"
    # except sqlite3.InterfaceError as e:
    #     print('[-] Sqlite interface error: {} Retrying...'.format(e))
    #     ctr = "0"
    # except sqlite3.Error:
    #     # time.sleep(0.10)
    #     ctr = "0"  # str(session["request_accepted_counter_demo"])

    if counterval is not None:
        ctr = client.get(session['insta_username']) 
		# str(counterval.counts)

    counterval = None
#    client = memcache.Client([('127.0.0.1', 11211)])
    ctr = client.get(session['insta_username'])

    if ctr == None:
        ctr = "0"
    print("counter: ", ctr)
    return ctr


@login_required
@users_blueprint.route('/accept_pending_requests', methods=['GET', 'POST'])
def accept_pending_requests():

    if request.method == 'POST':
        resp = 'Success'
        custom_number = request.form['customUserInputNumber']
        try:
            custom_number = int(custom_number)
        except:
            custom_number = int(custom_number[:-1])

        insta_obj = InstagramBot(
            session['insta_username'],
            session['insta_password'])
        insta_obj.login2()
        counts = insta_obj.pending_request_count()

        instagram_accept_request_count = custom_number

        try:
            if counts <= instagram_accept_request_count:
                insta_obj.accept_pending_requests(counts)
            else:
                insta_obj.accept_pending_requests(instagram_accept_request_count)
        except:
            resp = "No request to accept"

        return resp, 200

    try:
        user = Users.query.filter_by(
            insta_username=session['insta_username']).first()
        till_date = user.till_date
        last_day = (till_date - datetime.datetime.utcnow()).days

    except BaseException:
        last_day = None

    countval = Counter.query.filter_by(insta_username=session['insta_username']).first()

    if countval is None:
        newcounts = Counter(insta_username=session['insta_username'])
        db.session.add(newcounts)
        db.session.commit()
        countval = Counter.query.filter_by(insta_username=session['insta_username']).first()

    countval.counts = 0
    db.session.commit()

    return render_template(
        'AcceptRequests.html', instagram_username=session['insta_username'], last_day=last_day)


@users_blueprint.route('/request_accepted_count/<int:num>', methods=['GET', 'POST'])
def request_accepted_count(num):
    # counter =client.get(session['insta_username'])
	# Counter.query.filter_by(insta_username=session['insta_username']).first()
    # client = memcache.Client([('127.0.0.1', 11211)])
    ctr = client.get(session['insta_username'])
    
    # if counter is not None:
    #    ctr = counter.counts 

    return render_template('request_accepted_count.html', num=ctr)


@users_blueprint.route('/live_counter', methods=['GET', 'POST'])
def live_counter():

    if request.method == 'POST':
        try:

            instagram_username = request.form['instagram_username']
            session['live_counter'] = instagram_username
            response = requests.get(
                'https://www.instagram.com/web/search/topsearch/?query={un}'.format(un=instagram_username))
            resp = response.json()
            for i in resp['users']:
                if i['user']['username'] == instagram_username.lower():
                    count = i['user']['follower_count']
            name = '@' + \
                instagram_username[0].capitalize() + instagram_username[1:]
            return render_template('count_display.html',
                                   name=name, user_count=count)
        except BaseException:
            return render_template('LiveCounter.html')
    return render_template('LiveCounter.html')


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        instagram_username = request.form['userEmailID']
        instagram_password = request.form['userLoginPassword']

        #session['insta_username'] = instagram_username
        #session['insta_password'] = instagram_password
		# client.set(instagram_username, 0)
        # session['request_accepted_counter_demo'] = 0
        insta_bot = InstagramBot(instagram_username, instagram_password)
        insta_login_response = insta_bot.login()
        insta_bot.closeBrowser()

        if insta_login_response == False:
            msg = 'Invalid Credentails'
            return render_template('index.html', msg=msg)

        if insta_login_response:
            user_obj = Users.query.filter_by(
                insta_username=instagram_username).first()
			session['insta_username'] = instagram_username
			session['insta_password'] = instagram_password
			client.set(instagram_username, 0)
			
            if not user_obj:
                new_user = Users(insta_username=instagram_username)
                db.session.add(new_user)
                db.session.commit()

        user = Users.query.filter_by(insta_username=instagram_username).first()
        if insta_login_response and user is not None:
            user.is_subscribed = True
            user.till_date = datetime.datetime.utcnow() + timedelta(days=1)
            if user.is_subscribed:
                if datetime.datetime.utcnow() < user.till_date:
                    ok = login_user(user)
                    next = request.args.get('next')

                    if next is None or not next[0] == '/':
                        next = url_for('users.accept_pending_requests')
                    return redirect(next)

            if user.is_subscribed == False:
                try:
                    if datetime.datetime.utcnow() > user.till_date:
                        user.till_date = None
                        user.from_date = None
                        user.is_subscribed = False
                        db.session.commit()
                except BaseException:
                    ok = login_user(user)
                    next = request.args.get('next')
                    if next is None or not next[0] == '/':
                        next = url_for('core.pricing')
                    return redirect(next)

    return render_template('index.html')


@login_required
@users_blueprint.route('/logout')
def logout():
	client.set(instagram_username, 0)
    logout_user()
    return redirect(url_for('core.index'))

project/templates/Downloader.html
<!-- Designed & Developed by G Rohit
https://about.me/grohit -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.postimg.cc/B6kk4MyD/AM-icon.png" />
    <meta name="application-name" content="Pricing | AcceptMe,in">
    <meta name="description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta property="og:description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="keywords" content="Pending,request,instagram,insta,gram,telegram,facebook,gmail,whatsapp,intasgrm,graminsta,user,followers,acceptall,allow,users, pending instagram requests, downloader, insta DP, instagram profile pic, instagram profile, picture, download instagram video, video downloader, Acceptme,Accept,Me">
  <meta name="robots" content="index, follow">
  <meta name="copyright" content="Acceptme.in">
  <meta name="revisit-after" content="1 week">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- font awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
crossorigin="anonymous">

    <title>Accept ME</title>
<link rel="stylesheet" href="../static/acceptmestyling.css">

  </head>
  <body class="bg">
<div class="content">
    <div class="container">
    <!-- Image and text -->

      <nav class="navbar navbar-expand-lg fixed-top">
            <a class="navbar-brand" href="{{ url_for('core.index') }}">
                <img src="https://i.postimg.cc/5NWT002Q/Accept-ME-white.png" alt="accept me logo" width="120px" height="auto">
                    </a>
                  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse mobileMenubg" id="navbarCollapse">

              <ul class="navbar-nav ml-auto text-dark text-center">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Tools
                        </a>
                        <div class="dropdown-menu mobileMenuDropDownbg" aria-labelledby="navbarDropdown">
                        {% if current_user.is_authenticated %}
<a class="dropdown-item" href="{{ url_for('users.accept_pending_requests') }}">Accept Pending Requests</a>
{% endif %}
                          <a class="dropdown-item" href="{{ url_for('users.live_counter') }}">Live Counter</a>

                        </div>
                      </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.pricing') }}">Pricing</a>
                      </li>
                      <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.faq') }}">FAQ</a>
                          </li>


                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.contact') }}">Contact</a>
                      </li>
              </ul>
            </div>
          </nav>

    <div class="row">
        <div class="col-md-12">

        </div>
    </div>

</div>

<div class="container">
	<div class="row">
		<h1 class="text-white mt-5" >
			This page is currently not available. <br>	Please check later <i class="fa fa-sad"></i>
			<p>
				Go back to <a href="{{ url_for('core.index') }}" class="text-warning">Home Page</a>
			</p>

		</h1>

	</div>
</div>
<div class="push"></div>
</div>

<footer class="text-center footer">
    <a href="{{ url_for('core.index') }}" style="text-decoration: none">AcceptMe</a> <span class="color:#ffffff;">&copy; 2019</span>
</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

  <script>
        $(".toggle-password").click(function () {

            $(this).toggleClass("fa-eye fa-eye-slash");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
                input.attr("type", "text");
            } else {
                input.attr("type", "password");
            }

        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
<script>
  $(function () {
    $(document).scroll(function () {
      var $nav = $(".navbar-fixed-top");
      $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
    });
  });
</script>

</html>

project/templates/index.html
<!-- Designed & Developed by G Rohit
https://about.me/grohit -->
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.postimg.cc/B6kk4MyD/AM-icon.png" />
    <meta name="application-name" content="Pricing | AcceptMe,in">
    <meta name="description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta property="og:description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="keywords" content="Pending,request,instagram,insta,gram,telegram,facebook,gmail,whatsapp,intasgrm,graminsta,user,followers,acceptall,allow,users, pending instagram requests, downloader, insta DP, instagram profile pic, instagram profile, picture, download instagram video, video downloader, Acceptme,Accept,Me">
    <meta name="robots" content="index, follow">
    <meta name="copyright" content="Acceptme.in">
    <meta name="revisit-after" content="1 week">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
        crossorigin="anonymous">

    <title>Login | AcceptMe.in</title>
    <link rel="stylesheet" href="../static/acceptmestyling.css">

    <style media="screen">
    .farhaan {
        text-align: center;
        border: 1px solid green;
        background-color: orange;
        line-height: 7px;
        padding: 16px 0 0 0;
    }
    </style>

</head>

<body class="bg">
    <div class="content">
        <div class="container">
            <!-- Image and text -->

            <nav class="navbar navbar-expand-lg fixed-top">
                <a class="navbar-brand" href="{{ url_for('core.index') }}">
                    <img src="https://i.postimg.cc/5NWT002Q/Accept-ME-white.png" alt="accept me logo" width="120px"
                        height="auto">
                </a>
                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse mobileMenubg" id="navbarCollapse">

                    <ul class="navbar-nav ml-auto text-dark text-center ">
                        <li class="nav-item" id="activePage">
                            <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                Tools
                            </a>
                            <div class="dropdown-menu mobileMenuDropDownbg" aria-labelledby="navbarDropdown">

                                {% if current_user.is_authenticated %}
  <a class="dropdown-item" href="{{ url_for('users.accept_pending_requests', username='Farhaan') }}">Accept Pending Requests</a>
  {% endif %}

                                <a class="dropdown-item" href="{{ url_for('users.live_counter') }}">Live Counter</a>
                                <!-- <a class="dropdown-item" href="Downloader.html">Post/DP Downloader</a> -->
                                <!-- <a class="dropdown-item" href="MassDelete.html">Mass Post Delete</a> -->
                                <!-- <a class="dropdown-item" href="MassUnfollow.html">Mass Unfollow</a> -->
                            </div>
                        </li>




                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.pricing') }}">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.faq') }}">FAQ</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.contact') }}">Contact</a>
                        </li>



                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>

            <div class="row">
                <div class="col-md-12">
                    <form action="{{ url_for('users.login') }}" method="POST" class="text-center" onsubmit="return validateLogin()" name="loginForm">

                        <input type="text" name="userEmailID" id="loginUN" placeholder="ENTER YOUR INSTAGRAM USERNAME" > <br>
                        <!-- <p id="errorUserLoginEmail">testing error message</p> -->
                        <input type="password" class="" placeholder="ENTER YOUR INSTAGRAM PASSWORD" id="loginPW" name="userLoginPassword"
                            title="Please enter your password"> <span toggle="#loginPW" class="fa fa-fw fa-eye field-icon toggle-password"
                            style="cursor: pointer;"></span>
<br>
                        <button type="submit" id="loginBtn">Login</button> <br><br>

                    </form>

                    <!-- Modal for forgot password-->

                    <!-- Modal for forgot password ends -->

                    <!-- Modal for Sign up form-->
                    <div class="modal fade" id="signUpmodal" tabindex="-1" role="dialog" aria-labelledby="signUpmodalTitle"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content" style="
                background: #ffffffe1;">
                                <div class="modal-body text-center">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>


                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal for Sign up form ends -->

                </div>
            </div>

        </div>
        <!-- <div class="push"></div> -->
    </div>

    {% if msg %}
    <div class="farhaan">
      <p>{{ msg }}</p>
    </div>
    {% endif %}



    <footer class="text-center footer">
        <a href="{{ url_for('core.index') }}" style="text-decoration: none">AcceptMe</a> <span class="color:#ffffff;">&copy; 2019</span>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

<script>
    $(".toggle-password").click(function () {

        $(this).toggleClass("fa-eye fa-eye-slash");
        var input = $($(this).attr("toggle"));
        if (input.attr("type") == "password") {
            input.attr("type", "text");
        } else {
            input.attr("type", "password");
        }

    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })


</script>
<script src="../static/validations.js"></script>
</html>

project/templates/request_acceptor.html
<!-- Designed & Developed by G Rohit
https://about.me/grohit -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.postimg.cc/B6kk4MyD/AM-icon.png" />
   <meta name="application-name" content="Pricing | AcceptMe,in">
   <meta name="description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
   <meta property="og:description" content="An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
   <meta name="mobile-web-app-capable" content="yes">
   <meta name="keywords" content="Pending,request,instagram,insta,gram,telegram,facebook,gmail,whatsapp,intasgrm,graminsta,user,followers,acceptall,allow,users, pending instagram requests, downloader, insta DP, instagram profile pic, instagram profile, picture, download instagram video, video downloader, Acceptme,Accept,Me">
 <meta name="robots" content="index, follow">
 <meta name="copyright" content="Acceptme.in">
 <meta name="revisit-after" content="1 week">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- font awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
crossorigin="anonymous">

    <title>Accept ME</title>
<link rel="stylesheet" href="../static/acceptmestyling.css">


<link rel="stylesheet" href="http://github.hubspot.com/odometer/themes/odometer-theme-car.css" />
<script src="http://github.hubspot.com/odometer/odometer.js"></script>



  </head>
  <body class="bg">
<div class="content">
    <div class="container">
    <!-- Image and text -->

      <nav class="navbar navbar-expand-lg fixed-top">
            <a class="navbar-brand" href="{{ url_for('core.index') }}">
                <img src="https://i.postimg.cc/5NWT002Q/Accept-ME-white.png" alt="accept me logo" width="120px" height="auto">
                    </a>
                  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse mobileMenubg" id="navbarCollapse">

              <ul class="navbar-nav ml-auto text-dark text-center">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Tools
                        </a>
                        <div class="dropdown-menu mobileMenuDropDownbg" aria-labelledby="navbarDropdown">
                        {% if current_user.is_authenticated %}
<a class="dropdown-item" href="{{ url_for('users.accept_pending_requests') }}">Accept Pending Requests</a>
{% endif %}
                          <a class="dropdown-item" href="{{ url_for('users.live_counter') }}">Live Counter</a>

                        </div>
                      </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.pricing') }}">Pricing</a>
                      </li>
                      <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('core.faq') }}">FAQ</a>
                          </li>


                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.contact') }}">Contact</a>
                      </li>

                      {% if current_user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                      </li>
                      {% endif %}
              </ul>
            </div>
          </nav>

    <div class="row">
        <div class="col-md-12">

        </div>
    </div>

</div>


	<div class="row">







    <div class="col-md-12">
        <form action="{{ url_for('users.pending_request_count') }}" method="POST" class="text-center" onsubmit="return validateLogin()" name="loginForm">


          <input type="password" name="instagram_password" placeholder="ENTER YOUR INSTAGRAM PASSWORD"><br>
          <button type="submit" id="loginBtn">Submit</button> <br><br>
            <!-- <p id="errorUserLoginEmail">testing error message</p> -->

  <br>


        </form>


    </div>



	</div>
<div class="push"></div>
</div>

<footer class="text-center footer">
    <a href="{{ url_for('core.index') }}" style="text-decoration: none">AcceptMe</a> <span class="color:#ffffff;">&copy; 2019</span>
</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

  <script>
        $(".toggle-password").click(function () {

            $(this).toggleClass("fa-eye fa-eye-slash");
            var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
                input.attr("type", "text");
            } else {
                input.attr("type", "password");
            }

        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
<script>
  $(function () {
    $(document).scroll(function () {
      var $nav = $(".navbar-fixed-top");
      $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
    });
  });
</script>

<style>
.odometer {
    font-size: 100px;
}

setTimeout(function(){
    odometer.innerHTML = 454s55;
}, 1000);
</style>

</html>